services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    # TODO: remove port 80
    ports:
      - 80:80
      - 443:443
    # TODO: move volumes to /home/flfische/data
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped
    env_file: ".env"

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    # TODO: move volumes to /home/flfische/data
    volumes:
      - wp_data:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: unless-stopped
    env_file: ".env"
    secrets:
      - wp_db_password
      - wp_admin_password
      - wp_user_password

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    # TODO: move volumes to /home/flfische/data
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    env_file: ".env"
    secrets:
      - wp_db_password
      - wp_db_root_password

  redis:
    build: ./requirements/redis
    container_name: redis
    # TODO: move volumes to /home/flfische/data
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  adminer:
    build: ./requirements/adminer
    container_name: adminer
    ports:
      - 8080:80
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: unless-stopped

  portainer:
    build: ./requirements/portainer
    container_name: portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # TODO: move volumes to /home/flfische/data
      - portainer_data:/data
    networks:
      - inception
    restart: unless-stopped

  ftp:
    build: ./requirements/ftpserver
    container_name: ftp
    ports:
      - 21:21
      - 45000-45100:45000-45100
    volumes:
      # TODO: move volumes to /home/flfische/data
      - wp_data:/var/www/html
    networks:
      - inception
    restart: unless-stopped
    secrets:
      - ftp_password
    env_file: ".env"

  staticsite:
    build: ./requirements/staticsite
    container_name: staticsite
    ports:
      - 3000:3000
    networks:
      - inception
    restart: unless-stopped
    tty: true

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  db_data:
    name: 'db_data'
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/flfische/data/database"
  wp_data:
    name: 'wp_data'
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/flfische/data/web"
  portainer_data:
    name: 'portainer_data'
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/flfische/data/portainer"

secrets:
  wp_db_password:
    file: ../secrets/wp_db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  wp_db_root_password:
    file: ../secrets/wp_db_root_password.txt
