services:
  nginx:
    build: srcs/requirements/nginx
    container_name: nginx
    # TODO: remove port 80
    ports:
      - 80:80
      - 443:443
    # TODO: move volumes to /home/flfische/data
    volumes:
      - ../web:/var/www/html
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    restart: always
    env_file: ".env"

  wordpress:
    build: srcs/requirements/wordpress
    container_name: wordpress
    # TODO: move volumes to /home/flfische/data
    volumes:
      - ../web:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file: ".env"

  mariadb:
    build: srcs/requirements/mariadb
    container_name: mariadb
    # TODO: move volumes to /home/flfische/data
    volumes:
      - ../database:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    env_file: ".env"

networks:
  inception:
    name: inception
    driver: bridge
